### PR TITLE
Adds QueryID and QueryAnnotationID to Boards

### PR DESCRIPTION
**Pull request by tyler-boyd**

### CODE REVIEW

**Comment by kvrhdn** [comment]
Hi Tyler, sorry for the delayed review. Can you also update the tests in `board_test.go` and `query_spec_test.go`? Running the tests locally causes compilation errors:
```
$ go test .
# github.com/kvrhdn/go-honeycombio [github.com/kvrhdn/go-honeycombio.test]
./board_test.go:31:6: cannot use QuerySpec{...} (type QuerySpec) as type *QuerySpec in field value
./board_test.go:77:4: cannot use QuerySpec{...} (type QuerySpec) as type *QuerySpec in field value
./query_spec_test.go:62:5: cannot use query (type QuerySpec) as type *QuerySpec in field value
./query_spec_test.go:109:47: cannot use q (type QuerySpec) as type *QuerySpec in field value
./query_spec_test.go:150:47: cannot use q (type QuerySpec) as type *QuerySpec in field value
FAIL    github.com/kvrhdn/go-honeycombio [build failed]
FAIL
```

**Comment by tyler-boyd** [comment]
Thanksi @kvrhdn, I have updated the tests in this PR! They work for me locally, hopefully same for you.

**Review by kvrhdn — APPROVED** [review]
This is looking good thanks! This contains a breaking change, so it will be a version bump.

**Comment by kvrhdn** [comment]
By creating a release these changes are now also visible on pkg.go.dev: https://pkg.go.dev/github.com/kvrhdn/go-honeycombio@v0.3.0

**Comment by tyler-boyd** [comment]
:tada: Thanks! I shall update the other PRs to refer to the new version

**Pull request merged**
